export const queryKeys = {
  backendHealth: ["backend-health"] as const,
  summary: ["summary"] as const,
  jobs: (params: Record<string, unknown>) => ["jobs", params] as const,
  jobProgress: (jobId: string) => ["job-progress", jobId] as const,
  leads: (params: Record<string, unknown>) => ["leads", params] as const,
  leadFilterOptions: ["lead-filter-options"] as const,
  leadEmails: (leadId: number) => ["lead-emails", leadId] as const,
  campaigns: ["campaigns"] as const,
  campaign: (campaignId: number) => ["campaign", campaignId] as const,
  campaignLeads: (campaignId: number, params: Record<string, unknown>) => ["campaign-leads", campaignId, params] as const,
  emailSettings: ["email-settings"] as const,
  businessTypeEmailRules: ["business-type-email-rules"] as const,
  emailCategoryRules: ["email-category-rules"] as const,
  unknownEmailLocalParts: ["unknown-email-local-parts"] as const,
  exportLeads: ["export-leads"] as const,
};
